package cn.yx.entity;

public class WhsCompany {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.type
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Byte type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.image
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String image;
    private String imageUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.principal
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String principal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.phone
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.tele
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String tele;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.mail
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String mail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Long createTime;
    private String createTimeStr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company.url
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.id
     * @return  the value of whs_company.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.id
     * @param id  the value for whs_company.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.name
     * @return  the value of whs_company.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.name
     * @param name  the value for whs_company.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.type
     * @return  the value of whs_company.type
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.type
     * @param type  the value for whs_company.type
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.image
     * @return  the value of whs_company.image
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.image
     * @param image  the value for whs_company.image
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.principal
     * @return  the value of whs_company.principal
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.principal
     * @param principal  the value for whs_company.principal
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.phone
     * @return  the value of whs_company.phone
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.phone
     * @param phone  the value for whs_company.phone
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.tele
     * @return  the value of whs_company.tele
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.tele
     * @param tele  the value for whs_company.tele
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setTele(String tele) {
        this.tele = tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.mail
     * @return  the value of whs_company.mail
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.mail
     * @param mail  the value for whs_company.mail
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.status
     * @return  the value of whs_company.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.status
     * @param status  the value for whs_company.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.address
     * @return  the value of whs_company.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.address
     * @param address  the value for whs_company.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.create_time
     * @return  the value of whs_company.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.create_time
     * @param createTime  the value for whs_company.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company.url
     * @return  the value of whs_company.url
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company.url
     * @param url  the value for whs_company.url
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getCreateTimeStr() {
        return createTimeStr;
    }

    public void setCreateTimeStr(String createTimeStr) {
        this.createTimeStr = createTimeStr;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}