package cn.yx.entity;

public class WhsCompanyApply {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.principal
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String principal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.phone
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.tele
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String tele;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.mail
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String mail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.apply_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Long applyTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_company_apply.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.id
     * @return  the value of whs_company_apply.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.id
     * @param id  the value for whs_company_apply.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.name
     * @return  the value of whs_company_apply.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.name
     * @param name  the value for whs_company_apply.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.principal
     * @return  the value of whs_company_apply.principal
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.principal
     * @param principal  the value for whs_company_apply.principal
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.phone
     * @return  the value of whs_company_apply.phone
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.phone
     * @param phone  the value for whs_company_apply.phone
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.tele
     * @return  the value of whs_company_apply.tele
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.tele
     * @param tele  the value for whs_company_apply.tele
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setTele(String tele) {
        this.tele = tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.mail
     * @return  the value of whs_company_apply.mail
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.mail
     * @param mail  the value for whs_company_apply.mail
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.address
     * @return  the value of whs_company_apply.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.address
     * @param address  the value for whs_company_apply.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.apply_time
     * @return  the value of whs_company_apply.apply_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Long getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.apply_time
     * @param applyTime  the value for whs_company_apply.apply_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setApplyTime(Long applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_company_apply.status
     * @return  the value of whs_company_apply.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_company_apply.status
     * @param status  the value for whs_company_apply.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

}