package cn.yx.entity;

public class WhsDownloads {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.id
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.browses
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private Long browses;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.title
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.abstr
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private String abstr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.status
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.create_time
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private Long createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.annex
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private String annex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.annex_name
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private String annexName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.downs
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private Integer downs;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.author
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private String author;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_downloads.content
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.id
     * @return  the value of whs_downloads.id
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.id
     * @param id  the value for whs_downloads.id
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.browses
     * @return  the value of whs_downloads.browses
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public Long getBrowses() {
        return browses;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.browses
     * @param browses  the value for whs_downloads.browses
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setBrowses(Long browses) {
        this.browses = browses;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.title
     * @return  the value of whs_downloads.title
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.title
     * @param title  the value for whs_downloads.title
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.abstr
     * @return  the value of whs_downloads.abstr
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public String getAbstr() {
        return abstr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.abstr
     * @param abstr  the value for whs_downloads.abstr
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setAbstr(String abstr) {
        this.abstr = abstr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.status
     * @return  the value of whs_downloads.status
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.status
     * @param status  the value for whs_downloads.status
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.create_time
     * @return  the value of whs_downloads.create_time
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.create_time
     * @param createTime  the value for whs_downloads.create_time
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.annex
     * @return  the value of whs_downloads.annex
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public String getAnnex() {
        return annex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.annex
     * @param annex  the value for whs_downloads.annex
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setAnnex(String annex) {
        this.annex = annex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.annex_name
     * @return  the value of whs_downloads.annex_name
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public String getAnnexName() {
        return annexName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.annex_name
     * @param annexName  the value for whs_downloads.annex_name
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setAnnexName(String annexName) {
        this.annexName = annexName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.downs
     * @return  the value of whs_downloads.downs
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public Integer getDowns() {
        return downs;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.downs
     * @param downs  the value for whs_downloads.downs
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setDowns(Integer downs) {
        this.downs = downs;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.author
     * @return  the value of whs_downloads.author
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.author
     * @param author  the value for whs_downloads.author
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_downloads.content
     * @return  the value of whs_downloads.content
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_downloads.content
     * @param content  the value for whs_downloads.content
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}