package cn.yx.entity;

public class WhsHomepage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_homepage.time
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_homepage.address
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_homepage.logo
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_homepage.introduction
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_homepage.time
     *
     * @return the value of whs_homepage.time
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_homepage.time
     *
     * @param time the value for whs_homepage.time
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_homepage.address
     *
     * @return the value of whs_homepage.address
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_homepage.address
     *
     * @param address the value for whs_homepage.address
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_homepage.logo
     *
     * @return the value of whs_homepage.logo
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_homepage.logo
     *
     * @param logo the value for whs_homepage.logo
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_homepage.introduction
     *
     * @return the value of whs_homepage.introduction
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_homepage.introduction
     *
     * @param introduction the value for whs_homepage.introduction
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }
}