package cn.yx.entity;

public class WhsHistory {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.abstr
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String abstr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String createTimeStr;
    private Long createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.content
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.id
     * @return  the value of whs_history.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.id
     * @param id  the value for whs_history.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.name
     * @return  the value of whs_history.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.name
     * @param name  the value for whs_history.name
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.status
     * @return  the value of whs_history.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.status
     * @param status  the value for whs_history.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.abstr
     * @return  the value of whs_history.abstr
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getAbstr() {
        return abstr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.abstr
     * @param abstr  the value for whs_history.abstr
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setAbstr(String abstr) {
        this.abstr = abstr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.create_time
     * @return  the value of whs_history.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.create_time
     * @param createTime  the value for whs_history.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.content
     * @return  the value of whs_history.content
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.content
     * @param content  the value for whs_history.content
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getCreateTimeStr() {
        return createTimeStr;
    }

    public void setCreateTimeStr(String createTimeStr) {
        this.createTimeStr = createTimeStr;
    }
}