package cn.yx.entity;

import java.util.Date;

public class WhsHomepage {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.id
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.address
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.begin_time
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private Date beginTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.end_time
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private Date endTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.logo
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private String logo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.status
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.addre
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private String addre;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.tele
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private String tele;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.mail
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private String mail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.introduction
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.id
     * @return  the value of whs_homepage.id
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.id
     * @param id  the value for whs_homepage.id
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.address
     * @return  the value of whs_homepage.address
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.address
     * @param address  the value for whs_homepage.address
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.begin_time
     * @return  the value of whs_homepage.begin_time
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.begin_time
     * @param beginTime  the value for whs_homepage.begin_time
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.end_time
     * @return  the value of whs_homepage.end_time
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.end_time
     * @param endTime  the value for whs_homepage.end_time
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.logo
     * @return  the value of whs_homepage.logo
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.logo
     * @param logo  the value for whs_homepage.logo
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.status
     * @return  the value of whs_homepage.status
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.status
     * @param status  the value for whs_homepage.status
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.addre
     * @return  the value of whs_homepage.addre
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public String getAddre() {
        return addre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.addre
     * @param addre  the value for whs_homepage.addre
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setAddre(String addre) {
        this.addre = addre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.tele
     * @return  the value of whs_homepage.tele
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public String getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.tele
     * @param tele  the value for whs_homepage.tele
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setTele(String tele) {
        this.tele = tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.mail
     * @return  the value of whs_homepage.mail
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.mail
     * @param mail  the value for whs_homepage.mail
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.introduction
     * @return  the value of whs_homepage.introduction
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.introduction
     * @param introduction  the value for whs_homepage.introduction
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    private String time;
    private String logoUrl;

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getLogoUrl() {
        return logoUrl;
    }

    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
}