package cn.yx.entity;

public class WhsHistory {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.id
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.name
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_history.content
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.id
     * @return  the value of whs_history.id
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.id
     * @param id  the value for whs_history.id
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.name
     * @return  the value of whs_history.name
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.name
     * @param name  the value for whs_history.name
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_history.content
     * @return  the value of whs_history.content
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_history.content
     * @param content  the value for whs_history.content
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}