package cn.yx.entity;

public class WhsHomepage {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String time;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.logo
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String logo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_homepage.introduction
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.id
     * @return  the value of whs_homepage.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.id
     * @param id  the value for whs_homepage.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.time
     * @return  the value of whs_homepage.time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.time
     * @param time  the value for whs_homepage.time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.address
     * @return  the value of whs_homepage.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.address
     * @param address  the value for whs_homepage.address
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.logo
     * @return  the value of whs_homepage.logo
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.logo
     * @param logo  the value for whs_homepage.logo
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.status
     * @return  the value of whs_homepage.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.status
     * @param status  the value for whs_homepage.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_homepage.introduction
     * @return  the value of whs_homepage.introduction
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_homepage.introduction
     * @param introduction  the value for whs_homepage.introduction
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }
}