package cn.yx.entity;

public class WhsMedia {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.id
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.name
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.type
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private Byte type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.image
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String image;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.principal
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String principal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.phone
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.tele
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String tele;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.mail
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String mail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.address
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.status
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.apply_time
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private Long applyTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_media.url
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.id
     * @return  the value of whs_media.id
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.id
     * @param id  the value for whs_media.id
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.name
     * @return  the value of whs_media.name
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.name
     * @param name  the value for whs_media.name
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.type
     * @return  the value of whs_media.type
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.type
     * @param type  the value for whs_media.type
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.image
     * @return  the value of whs_media.image
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.image
     * @param image  the value for whs_media.image
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.principal
     * @return  the value of whs_media.principal
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.principal
     * @param principal  the value for whs_media.principal
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.phone
     * @return  the value of whs_media.phone
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.phone
     * @param phone  the value for whs_media.phone
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.tele
     * @return  the value of whs_media.tele
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.tele
     * @param tele  the value for whs_media.tele
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setTele(String tele) {
        this.tele = tele;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.mail
     * @return  the value of whs_media.mail
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.mail
     * @param mail  the value for whs_media.mail
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.address
     * @return  the value of whs_media.address
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.address
     * @param address  the value for whs_media.address
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.status
     * @return  the value of whs_media.status
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.status
     * @param status  the value for whs_media.status
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.apply_time
     * @return  the value of whs_media.apply_time
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public Long getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.apply_time
     * @param applyTime  the value for whs_media.apply_time
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setApplyTime(Long applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_media.url
     * @return  the value of whs_media.url
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_media.url
     * @param url  the value for whs_media.url
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }
}