package cn.yx.entity;

public class WhsNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_news.id
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_news.title
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_news.url
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_news.status
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_news.create_time
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_news.author
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whs_news.content
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_news.id
     *
     * @return the value of whs_news.id
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_news.id
     *
     * @param id the value for whs_news.id
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_news.title
     *
     * @return the value of whs_news.title
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_news.title
     *
     * @param title the value for whs_news.title
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_news.url
     *
     * @return the value of whs_news.url
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_news.url
     *
     * @param url the value for whs_news.url
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_news.status
     *
     * @return the value of whs_news.status
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_news.status
     *
     * @param status the value for whs_news.status
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_news.create_time
     *
     * @return the value of whs_news.create_time
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_news.create_time
     *
     * @param createTime the value for whs_news.create_time
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_news.author
     *
     * @return the value of whs_news.author
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_news.author
     *
     * @param author the value for whs_news.author
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whs_news.content
     *
     * @return the value of whs_news.content
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whs_news.content
     *
     * @param content the value for whs_news.content
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}