package cn.yx.entity;

public class WhsSliders {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_sliders.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_sliders.img_key
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String imgKey;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_sliders.title
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_sliders.url
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_sliders.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column whs_sliders.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_sliders.id
     * @return  the value of whs_sliders.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_sliders.id
     * @param id  the value for whs_sliders.id
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_sliders.img_key
     * @return  the value of whs_sliders.img_key
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getImgKey() {
        return imgKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_sliders.img_key
     * @param imgKey  the value for whs_sliders.img_key
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setImgKey(String imgKey) {
        this.imgKey = imgKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_sliders.title
     * @return  the value of whs_sliders.title
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_sliders.title
     * @param title  the value for whs_sliders.title
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_sliders.url
     * @return  the value of whs_sliders.url
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_sliders.url
     * @param url  the value for whs_sliders.url
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_sliders.status
     * @return  the value of whs_sliders.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_sliders.status
     * @param status  the value for whs_sliders.status
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column whs_sliders.create_time
     * @return  the value of whs_sliders.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column whs_sliders.create_time
     * @param createTime  the value for whs_sliders.create_time
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    private String src;

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }
    
}