spring:
  profiles: test
  
datasource: 
  url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
  username: root
  password: tiger
  driver-class-name: com.mysql.jdbc.Driver
  test-while-idle: true
  validation-query: SELECT 1
  time-between-eviction-runs-millis: 300000

file:
  url: http://39.108.95.14:8888