package cn.yx.mapper;

import cn.yx.entity.WhsArticle;
import org.apache.ibatis.jdbc.SQL;

public class WhsArticleSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whs_article
     *
     * @mbg.generated Wed Oct 25 16:59:29 CST 2017
     */
    public String insertSelective(WhsArticle record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("whs_article");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getParent() != null) {
            sql.VALUES("parent", "#{parent,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getModifyTime() != null) {
            sql.VALUES("modify_time", "#{modifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAuthor() != null) {
            sql.VALUES("author", "#{author,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            sql.VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whs_article
     *
     * @mbg.generated Wed Oct 25 16:59:29 CST 2017
     */
    public String updateByPrimaryKeySelective(WhsArticle record) {
        SQL sql = new SQL();
        sql.UPDATE("whs_article");
        
        if (record.getParent() != null) {
            sql.SET("parent = #{parent,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{modifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAuthor() != null) {
            sql.SET("author = #{author,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}