package cn.yx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.yx.entity.WhsHistory;

public interface WhsHistoryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    @Delete({ "delete from whs_history", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @Insert({ "insert into whs_history (id, name, ", "status, abstr, create_time, ", "content)",
            "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
            "#{status,jdbcType=TINYINT}, #{abstr,jdbcType=VARCHAR}, #{createTime,jdbcType=BIGINT}, ",
            "#{content,jdbcType=LONGVARCHAR})" })
    int insert(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @InsertProvider(type = WhsHistorySqlProvider.class, method = "insertSelective")
    int insertSelective(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    @Select({ "select", "id, name, status, abstr, create_time, content", "from whs_history",
            "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.TINYINT),
            @Result(column = "abstr", property = "abstr", jdbcType = JdbcType.VARCHAR),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.BIGINT),
            @Result(column = "content", property = "content", jdbcType = JdbcType.LONGVARCHAR) })
    WhsHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    @UpdateProvider(type = WhsHistorySqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    @Update({ "update whs_history", "set name = #{name,jdbcType=VARCHAR},", "status = #{status,jdbcType=TINYINT},",
            "abstr = #{abstr,jdbcType=VARCHAR},", "create_time = #{createTime,jdbcType=BIGINT},",
            "content = #{content,jdbcType=LONGVARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKeyWithBLOBs(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Aug 13 17:16:41 CST 2017
     */
    @Update({ "update whs_history", "set name = #{name,jdbcType=VARCHAR},", "status = #{status,jdbcType=TINYINT},",
            "abstr = #{abstr,jdbcType=VARCHAR},", "create_time = #{createTime,jdbcType=BIGINT}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(WhsHistory record);

    @SelectProvider(type = WhsHistorySqlProvider.class, method = "listSelective")
    List<WhsHistory> list(Integer status, Integer limit, Integer offset);
    
    @SelectProvider(type = WhsHistorySqlProvider.class, method = "countSelective")
    int count(Integer status);
}