package cn.yx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.yx.entity.WhsHomepage;

public interface WhsHomepageMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    @Delete({ "delete from whs_homepage", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    @Insert({ "insert into whs_homepage (id, time, ", "address, logo, status, ", "introduction)",
            "values (#{id,jdbcType=INTEGER}, #{time,jdbcType=VARCHAR}, ",
            "#{address,jdbcType=VARCHAR}, #{logo,jdbcType=VARCHAR}, #{status,jdbcType=TINYINT}, ",
            "#{introduction,jdbcType=LONGVARCHAR})" })
    int insert(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    @InsertProvider(type = WhsHomepageSqlProvider.class, method = "insertSelective")
    int insertSelective(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    @Select({ "select", "id, time, address, logo, status, introduction", "from whs_homepage",
            "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "time", property = "time", jdbcType = JdbcType.VARCHAR),
            @Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
            @Result(column = "logo", property = "logo", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.TINYINT),
            @Result(column = "introduction", property = "introduction", jdbcType = JdbcType.LONGVARCHAR) })
    WhsHomepage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    @UpdateProvider(type = WhsHomepageSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    @Update({ "update whs_homepage", "set time = #{time,jdbcType=VARCHAR},", "address = #{address,jdbcType=VARCHAR},",
            "logo = #{logo,jdbcType=VARCHAR},", "status = #{status,jdbcType=TINYINT},",
            "introduction = #{introduction,jdbcType=LONGVARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKeyWithBLOBs(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Wed Aug 09 09:52:41 CST 2017
     */
    @Update({ "update whs_homepage", "set time = #{time,jdbcType=VARCHAR},", "address = #{address,jdbcType=VARCHAR},",
            "logo = #{logo,jdbcType=VARCHAR},", "status = #{status,jdbcType=TINYINT}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(WhsHomepage record);

    @Select({
        "select ",
        "time, address, logo, introduction",
        "from whs_homepage"
    })
    @Results({
        @Result(column="time", property="time", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="introduction", property="introduction", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<WhsHomepage> selectAll();
    
    @Select("SELECT max(id) + 1 FROM fxb_announcement")
    Integer getLastId();
}