package cn.yx.mapper;

import cn.yx.entity.WhsHistory;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WhsHistoryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    @Delete({ "delete from whs_history", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @Insert({ "insert into whs_history (id, name, ", "content)",
            "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ", "#{content,jdbcType=LONGVARCHAR})" })
    int insert(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @InsertProvider(type = WhsHistorySqlProvider.class, method = "insertSelective")
    int insertSelective(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    @Select({ "select", "id, name, content", "from whs_history", "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
            @Result(column = "content", property = "content", jdbcType = JdbcType.LONGVARCHAR) })
    WhsHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    @UpdateProvider(type = WhsHistorySqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    @Update({ "update whs_history", "set name = #{name,jdbcType=VARCHAR},", "content = #{content,jdbcType=LONGVARCHAR}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKeyWithBLOBs(WhsHistory record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 30 19:58:31 CST 2017
     */
    @Update({ "update whs_history", "set name = #{name,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(WhsHistory record);

    @SelectProvider(type = WhsHistorySqlProvider.class, method = "listSelective")
    List<WhsHistory> list(Integer limit, Integer offset);
    
    @SelectProvider(type = WhsHistorySqlProvider.class, method = "countSelective")
    int count();
}