package cn.yx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import cn.yx.entity.WhsHomepage;

public interface WhsHomepageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whs_homepage
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    @Insert({
        "insert into whs_homepage (time, address, ",
        "logo, introduction)",
        "values (#{time,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{logo,jdbcType=VARCHAR}, #{introduction,jdbcType=LONGVARCHAR})"
    })
    int insert(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whs_homepage
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    @InsertProvider(type=WhsHomepageSqlProvider.class, method="insertSelective")
    int insertSelective(WhsHomepage record);
    
    @Select({
        "select ",
        "time, address, logo, introduction",
        "from whs_homepage",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="time", property="time", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="introduction", property="introduction", jdbcType=JdbcType.LONGVARCHAR)
    })
    WhsHomepage selectByPrimaryKey(Integer id);
    
    @Select({
        "select ",
        "time, address, logo, introduction",
        "from whs_homepage"
    })
    @Results({
        @Result(column="time", property="time", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="introduction", property="introduction", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<WhsHomepage> selectAll();
}