package cn.yx.mapper;

import cn.yx.entity.WhsHomepage;
import org.apache.ibatis.jdbc.SQL;

public class WhsHomepageSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table whs_homepage
     *
     * @mbg.generated Thu Jul 13 16:24:58 CST 2017
     */
    public String insertSelective(WhsHomepage record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("whs_homepage");
        
        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getLogo() != null) {
            sql.VALUES("logo", "#{logo,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduction() != null) {
            sql.VALUES("introduction", "#{introduction,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }
}