package cn.yx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.yx.entity.WhsHomepage;

public interface WhsHomepageMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    @Delete({ "delete from whs_homepage", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Thu Dec 14 11:03:00 CST 2017
     */
    @Insert({ "insert into whs_homepage (id, address, ", "begin_time, end_time, ", "logo, status, addre, ",
            "tele, mail, introduction)", "values (#{id,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
            "#{beginTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
            "#{logo,jdbcType=VARCHAR}, #{status,jdbcType=TINYINT}, #{addre,jdbcType=VARCHAR}, ",
            "#{tele,jdbcType=VARCHAR}, #{mail,jdbcType=VARCHAR}, #{introduction,jdbcType=LONGVARCHAR})" })
    int insert(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Thu Dec 14 11:03:01 CST 2017
     */
    @InsertProvider(type = WhsHomepageSqlProvider.class, method = "insertSelective")
    int insertSelective(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Thu Dec 14 11:03:01 CST 2017
     */
    @Select({ "select", "id, address, begin_time, end_time, logo, status, addre, tele, mail, introduction",
            "from whs_homepage", "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
            @Result(column = "begin_time", property = "beginTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "end_time", property = "endTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "logo", property = "logo", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.TINYINT),
            @Result(column = "addre", property = "addre", jdbcType = JdbcType.VARCHAR),
            @Result(column = "tele", property = "tele", jdbcType = JdbcType.VARCHAR),
            @Result(column = "mail", property = "mail", jdbcType = JdbcType.VARCHAR),
            @Result(column = "introduction", property = "introduction", jdbcType = JdbcType.LONGVARCHAR) })
    WhsHomepage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Thu Dec 14 11:03:01 CST 2017
     */
    @UpdateProvider(type = WhsHomepageSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Thu Dec 14 11:03:01 CST 2017
     */
    @Update({ "update whs_homepage", "set address = #{address,jdbcType=VARCHAR},",
            "begin_time = #{beginTime,jdbcType=TIMESTAMP},", "end_time = #{endTime,jdbcType=TIMESTAMP},",
            "logo = #{logo,jdbcType=VARCHAR},", "status = #{status,jdbcType=TINYINT},",
            "addre = #{addre,jdbcType=VARCHAR},", "tele = #{tele,jdbcType=VARCHAR},",
            "mail = #{mail,jdbcType=VARCHAR},", "introduction = #{introduction,jdbcType=LONGVARCHAR}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKeyWithBLOBs(WhsHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_homepage
     * @mbg.generated  Thu Dec 14 11:03:01 CST 2017
     */
    @Update({ "update whs_homepage", "set address = #{address,jdbcType=VARCHAR},",
            "begin_time = #{beginTime,jdbcType=TIMESTAMP},", "end_time = #{endTime,jdbcType=TIMESTAMP},",
            "logo = #{logo,jdbcType=VARCHAR},", "status = #{status,jdbcType=TINYINT},",
            "addre = #{addre,jdbcType=VARCHAR},", "tele = #{tele,jdbcType=VARCHAR},", "mail = #{mail,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(WhsHomepage record);

    @Select({
        "select ",
        "time, address, logo, introduction",
        "from whs_homepage"
    })
    @Results({
        @Result(column="time", property="time", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR),
        @Result(column="introduction", property="introduction", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<WhsHomepage> selectAll();
    
    @Select("SELECT max(id) + 1 FROM whs_homepage")
    Integer getLastId();
}