package cn.yx.mapper;

import cn.yx.entity.WhsHistory;
import org.apache.ibatis.jdbc.SQL;

public class WhsHistorySqlProvider {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 23 15:42:13 CST 2017
     */
    public String insertSelective(WhsHistory record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("whs_history");
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        if (record.getContent() != null) {
            sql.VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_history
     * @mbg.generated  Sun Jul 23 15:42:13 CST 2017
     */
    public String updateByPrimaryKeySelective(WhsHistory record) {
        SQL sql = new SQL();
        sql.UPDATE("whs_history");
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        if (record.getContent() != null) {
            sql.SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }
    
    public String listSelective(Integer limit, Integer offset) {
        SQL sql = new SQL();
        sql.SELECT("*");
        sql.FROM("whs_history");

        if (limit != -1) {
            return sql + " limit " + limit + " OFFSET " + offset;
        } else {
            return sql.toString();
        }
    }

    public String countSelective() {
        SQL sql = new SQL();
        sql.SELECT("count(*)");
        sql.FROM("whs_history");
        return sql.toString();
    }
}