package cn.yx.mapper;

import org.apache.ibatis.jdbc.SQL;

import cn.yx.entity.WhsNews;

public class WhsNewsSqlProvider {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 07 21:32:02 CST 2017
     */
    public String insertSelective(WhsNews record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("whs_news");
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        if (record.getBrowses() != null) {
            sql.VALUES("browses", "#{browses,jdbcType=BIGINT}");
        }
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        if (record.getUrl() != null) {
            sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=TINYINT}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=BIGINT}");
        }
        if (record.getAuthor() != null) {
            sql.VALUES("author", "#{author,jdbcType=VARCHAR}");
        }
        if (record.getParent() != null) {
            sql.VALUES("parent", "#{parent,jdbcType=TINYINT}");
        }
        if (record.getContent() != null) {
            sql.VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 07 21:32:02 CST 2017
     */
    public String updateByPrimaryKeySelective(WhsNews record) {
        SQL sql = new SQL();
        sql.UPDATE("whs_news");
        if (record.getBrowses() != null) {
            sql.SET("browses = #{browses,jdbcType=BIGINT}");
        }
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        if (record.getUrl() != null) {
            sql.SET("url = #{url,jdbcType=VARCHAR}");
        }
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=TINYINT}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=BIGINT}");
        }
        if (record.getAuthor() != null) {
            sql.SET("author = #{author,jdbcType=VARCHAR}");
        }
        if (record.getParent() != null) {
            sql.SET("parent = #{parent,jdbcType=TINYINT}");
        }
        if (record.getContent() != null) {
            sql.SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }

    public String listSelective(Integer status, Integer parent, Integer limit, Integer offset) {
        SQL sql = new SQL();
        sql.SELECT("*");
        sql.SELECT("create_time as createTime");
        sql.FROM("whs_news");
        
        if(status != null && status != -1) {
            sql.WHERE("status = #{arg0,jdbcType=TINYINT}");
        } else {
            sql.WHERE("status != -1 ");
        }
        if(parent!= null && parent >= 0) {
            sql.WHERE("parent = #{arg1,jdbcType=TINYINT}");
        }
        sql.ORDER_BY("createTime desc");
        
        if (limit != -1) {
            return sql + " limit " + limit + " OFFSET " + offset;
        } else {
            return sql.toString();
        }
    }
    
    public String countSelective(Integer status, Integer parent) {
        SQL sql = new SQL();
        sql.SELECT("count(*)");
        sql.FROM("whs_news");
        
        if(status != null && status != -1) {
            sql.WHERE("status = #{arg0,jdbcType=TINYINT}");
        } else {
            sql.WHERE("status != -1 ");
        }
        if(parent!= null && parent >= 0) {
            sql.WHERE("parent = #{arg1,jdbcType=TINYINT}");
        }
        
        return sql.toString();
    }
}