package cn.yx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.yx.entity.WhsNews;

public interface WhsNewsMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    @Delete({ "delete from whs_news", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @Insert({ "insert into whs_news (id, browses, ", "title, abstr, url, ", "status, create_time, ", "author, parent, ",
            "content)", "values (#{id,jdbcType=INTEGER}, #{browses,jdbcType=BIGINT}, ",
            "#{title,jdbcType=VARCHAR}, #{abstr,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
            "#{status,jdbcType=TINYINT}, #{createTime,jdbcType=BIGINT}, ",
            "#{author,jdbcType=VARCHAR}, #{parent,jdbcType=TINYINT}, ", "#{content,jdbcType=LONGVARCHAR})" })
    int insert(WhsNews record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @InsertProvider(type = WhsNewsSqlProvider.class, method = "insertSelective")
    int insertSelective(WhsNews record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    @Select({ "select", "id, browses, title, abstr, url, status, create_time, author, parent, content", "from whs_news",
            "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "browses", property = "browses", jdbcType = JdbcType.BIGINT),
            @Result(column = "title", property = "title", jdbcType = JdbcType.VARCHAR),
            @Result(column = "abstr", property = "abstr", jdbcType = JdbcType.VARCHAR),
            @Result(column = "url", property = "url", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.TINYINT),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.BIGINT),
            @Result(column = "author", property = "author", jdbcType = JdbcType.VARCHAR),
            @Result(column = "parent", property = "parent", jdbcType = JdbcType.TINYINT),
            @Result(column = "content", property = "content", jdbcType = JdbcType.LONGVARCHAR) })
    WhsNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    @UpdateProvider(type = WhsNewsSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WhsNews record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    @Update({ "update whs_news", "set browses = #{browses,jdbcType=BIGINT},", "title = #{title,jdbcType=VARCHAR},",
            "abstr = #{abstr,jdbcType=VARCHAR},", "url = #{url,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=TINYINT},", "create_time = #{createTime,jdbcType=BIGINT},",
            "author = #{author,jdbcType=VARCHAR},", "parent = #{parent,jdbcType=TINYINT},",
            "content = #{content,jdbcType=LONGVARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKeyWithBLOBs(WhsNews record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table whs_news
     * @mbg.generated  Mon Aug 14 20:03:18 CST 2017
     */
    @Update({ "update whs_news", "set browses = #{browses,jdbcType=BIGINT},", "title = #{title,jdbcType=VARCHAR},",
            "abstr = #{abstr,jdbcType=VARCHAR},", "url = #{url,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=TINYINT},", "create_time = #{createTime,jdbcType=BIGINT},",
            "author = #{author,jdbcType=VARCHAR},", "parent = #{parent,jdbcType=TINYINT}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(WhsNews record);

    @SelectProvider(type = WhsNewsSqlProvider.class, method = "listSelective")
    List<WhsNews> list(Integer status, Integer parent, long beginTime, long endTime, String query, Integer limit, Integer offset);
    
    @SelectProvider(type = WhsNewsSqlProvider.class, method = "countSelective")
    int count(Integer status, Integer parent, long beginTime, long endTime, String query);
    
    @Select("SELECT max(id) + 1 FROM whs_news")
    Integer getLastId();
}